pipeline {
    agent any
    stages {
        stage('Compile Stage') {
		steps {
				withMaven(maven: "maven_3.0.5",
					 )
				 sh "mvn clean compile"
            }
        }
        stage('Code Quality Analysis Stage') {
		steps {
				withMaven(maven: "maven_3.0.5",
					 )
				 sh "mvn sonar:sonar"
            }
        }
        stage('WAR Generation Stage') {
            steps {
				withMaven(maven: "maven_3.0.5",
					 )
				 sh "mvn spackage"
            }
        }
    }
}
