pipeline {
    agent any
    stages {
        stage('Compile Stage') {
		steps {
			withMaven(maven: "maven_3.0.5"){
			         sh "cd /var/lib/jenkins/workspace/pipeline-test/demo"
				 sh "mvn clean compile --file /var/lib/jenkins/workspace/pipeline-test/demo/pom.xml"
			}
            }
        }
        stage('Code Quality Analysis Stage') {
		steps {
			withMaven(maven: "maven_3.0.5"){
			         
				 sh "mvn sonar:sonar"
			}
            }
        }
        stage('WAR Generation Stage') {
            steps {
		    withMaven(maven: "maven_3.0.5"){
			
		        sh "mvn package"
		    }
            }
        }
    }
}
